In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
# Matrix Addition

A = np.array([[-4, 6, 3],[0, 1, 2]])
B = np.array([[5, -1, 0],
              [3, 1, 0]])

print(f'A + B = {A+B}')

A + B = [[1 5 3]
 [3 2 2]]


In [3]:
# Scalar Multiplication
A = np.array([[-4, 6, 3],[0, 1, 2]])

# 3 times A

print(f' Three times A = {3*A}')

# two-fifths A
print(f'Two-fifths of A = {(2/5)*A}')

 Three times A = [[-12  18   9]
 [  0   3   6]]
Two-fifths of A = [[-1.6  2.4  1.2]
 [ 0.   0.4  0.8]]


In [4]:
# Zero Matrix or Null Matrix
Z = np.zeros((3,3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# Identity Matrix 4x4
I_4 = np.eye(4)
print(I_4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
# Matrix Multiplication
A = np.array([[3, 5, -1],
              [4, 0, 2],
              [-6,-3,2]])
B = np.array([[2,-2,3,1],
              [5,0,7,8],
              [9,-4,1,1]])

print(A@B)

[[ 22  -2  43  42]
 [ 26 -16  14   6]
 [ -9   4 -37 -28]]


In [7]:
# Matrix multiplication function
# computationally inefficient
# TODO: make it computationally efficient
def mat_mult(A,B):
    i,j = A.shape
    j,k = B.shape
    C = np.zeros((i,k))
    for i in range(A.shape[0]):
        for k in range(B.shape[1]):
            for j in range(B.shape[0]):

                C[i][k] += (A[i][j] * B[j][k])
    return C       
            

In [8]:
# Matrix Multiplication
A = np.array([[3, 5, -1],
              [4, 0, 2],
              [-6,-3,2]])
B = np.array([[2,-2,3,1],
              [5,0,7,8],
              [9,-4,1,1]])
C = mat_mult(A, B)
C

array([[ 22.,  -2.,  43.,  42.],
       [ 26., -16.,  14.,   6.],
       [ -9.,   4., -37., -28.]])

In [9]:
# AB != BA
# Matrix Multiplication is not commuatative

A = np.random.randint(low=-100,high=100,size=(2,2))
B = np.random.randint(-100,100,size=(2,2))
print(f'Matrix A: {A}')
print(f'Matrix B: {B}')
print(f'A X B: {A@B}')
print(f'B X A: {B@A}')

Matrix A: [[ 40 -70]
 [-71 -45]]
Matrix B: [[-24 -98]
 [-50 -88]]
A X B: [[ 2540  2240]
 [ 3954 10918]]
B X A: [[5998 6090]
 [4248 7460]]


#### Properties of Matrix Multiplication

- (kA)B = k(AB) = A(kB); or simply kAB

Associative Law
- A(BC) = (AB)C; simply ABC

Distributive Law
- (A+B)C = AC + BC
- C(A+B) = CA + CB

In [10]:
# Transpose of Matrices and Vectors(row or column matrices)

A = np.random.randint(low=-10,high=10,size=(2,3))
print(f'Matrix A:\n {A}\n')
# Transpose of Matrix A is
print(f'A.T =\n {A.T}\n')

B = np.random.randint(-10,10,(3,1))
print(f'Matrix B:\n {B}\n')
# Transpose of Matrix B is
print(f'B.T =\n {B.T}')


Matrix A:
 [[-2  2  0]
 [-3 -5  6]]

A.T =
 [[-2 -3]
 [ 2 -5]
 [ 0  6]]

Matrix B:
 [[ 4]
 [-9]
 [-9]]

B.T =
 [[ 4 -9 -9]]


#### Rules for transposition:

- (A.T).T = A
- (A+B).T = B.T + A.T
- (cA).T = c(A.T)
- (AB).T = (B.T) x (A.T)

In [11]:
# Symmetric Matrix
# A.T = A
# symmetric along principal diagonal

A = np.array([[20,10,5],
             [10, 2, 4],
             [5,4,-1]])
print(f'Matrix A:\n {A}\n')

# Transpose of Matrix A is
print(f'A.T =\n {A.T}\n')

#for the given A, is A.T == A ?
print((A.T==A).all())

Matrix A:
 [[20 10  5]
 [10  2  4]
 [ 5  4 -1]]

A.T =
 [[20 10  5]
 [10  2  4]
 [ 5  4 -1]]

True


In [12]:
# skew-symmetric matrix
# A.T = -A
# diagonal elements are zero and other elements are additive inverses over the 'zero' diagonal.
A = np.array([[0,10,-5],
             [-10, 0, -4],
             [5,4,0]])
print(f'Matrix A:\n {A}\n')

# Transpose of Matrix A is
print(f'A.T =\n {A.T}\n')

#for the given A, is A.T == A ?
print(f"is A.T == A: {(A.T==A).all()}",end='\n\n')

#for the given A, is A.T == A ?
print(f"is A.T == -A: {(A.T==-A).all()}",end='\n\n')


Matrix A:
 [[  0  10  -5]
 [-10   0  -4]
 [  5   4   0]]

A.T =
 [[  0 -10   5]
 [ 10   0   4]
 [ -5  -4   0]]

is A.T == A: False

is A.T == -A: True



In [14]:
# How to generate a symmetric matrix given any square matrix?
# If given matrix A. Then, A X (A.T)  is always symmetric.

A = np.random.randint(low=-10,high=10,size=(3,3))
print(f'Matrix A:\n {A}\n')
# Transpose of Matrix A is
print(f'A.T =\n {A.T}\n')

# A X A.T

print(f'A X A.T = \n {A@A.T}\n')

#for the given A, is A.T == A ?
print(f"is A x A.T == (AxA.T).T :\n {(A@A.T==(A@A.T).T).all()}",end='\n\n')


Matrix A:
 [[-1 -6 -7]
 [-7  9 -9]
 [ 2  9 -4]]

A.T =
 [[-1 -7  2]
 [-6  9  9]
 [-7 -9 -4]]

A X A.T = 
 [[ 86  16 -28]
 [ 16 211 103]
 [-28 103 101]]

is A x A.T == (AxA.T).T :
 True



In [44]:
### Solving system of linear equations
# AX = B
# X = inverse(A) B

A = np.array([[-1, -1, -5],
       [ 6, -9,  2],
       [-7,  0, -4]])

B = np.array([[3],
              [4],
              [6]])

X = np.linalg.inv(A) @ B
X

array([[-0.7063197 ],
       [-0.9739777 ],
       [-0.26394052]])

In [48]:
# comparing float values gives errors(not recommended)
# calculations involving floats will induce small errors
print(f'2.001 * 2.0001 = {2.001 * 2.0001}\n')

print(f'AX:\n {A@X}\n')
print(f'B:\n {B}\n')

print(f'A@X == B :\n {A@X == B}')

2.001 * 2.0001 = 4.0022001000000005

AX:
 [[3.]
 [4.]
 [6.]]

B:
 [[3]
 [4]
 [6]]

A@X == B :
 [[ True]
 [False]
 [False]]


In [37]:
np.round(A@X) == np.round(B)

array([[ True],
       [ True],
       [ True]])

In [60]:
# System of linear equations with no solution

A = np.array([[3,2,1],
             [0, -0.33, 0.33],
             [0, -2, 2]])
B = np.array([[3],
             [-2],
             [0]])

# Raises error
try:
    X = np.linalg.inv(A@B)
except Exception as e:
    print(e.__class__.__name__)
    print(e)

LinAlgError
Last 2 dimensions of the array must be square
